config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'

  devise_for :users, controllers: {registrations: 'users/registrations'}

  resources :users,only: [:show,:index,:edit,:update]
  get 'users/:id/follows' => "users#follows", as: "follows"
  get 'users/:id/followers' => "users#followers", as: "followers"
  resources :books do
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  post 'follow/:id' => "relationships#create", as: "follow"
  delete 'unfollow/:id' => "relationships#destroy", as: "unfollow"
  get 'search' => "search#action", as: "search"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :content, presence: true, length:{maximum:400}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = @book.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      render "create.js.erb"
    else
      flash[:danger] = "投稿できませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    unless @comment.user_id == current_user.id
      redirect_back(fallback_location: root_path)
    else
      @comment.destroy
      render "destroy.js.erb"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :book_id)
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_count.html.erb
<p><%= @book.comments.count %>件コメント</p>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <% unless comment.id.nil? %>
    <div id="comment-<%= comment.id %>" class="comment-box">
      <div class="comment-profile">
        <%= attachment_image_tag comment.user, :profile_image, fallback: "no_image.jpg", class:"comment-image", size: "40x40" %>
        <p><%= link_to "@#{comment.user.name}", user_path(comment.user.id) %></p>
      </div>
      <div class="comment-text">
        <div class="comment-entry">
          <%= comment.content %>
        </div>
      </div>
      <div class="comment-date pull-right">
        <% if comment.user == current_user %>
          <%= link_to "削除", book_comment_path(book_id:@book.id, id:comment.id), method: :delete, remote: true, class: "comment_destroy" %>
        <% end %>
        <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
      </div>
      <hr>
    </div>
  <% end %>
<% end %>

app/views/comments/create.js.erb
$("#comments-area").html("<%= j(render 'comments/index', {comments:@book.comments}) %>")
$("textarea").val('')
$(".comment-count").html("<%= j(render 'comments/count', {comments:@book.comments}) %>")

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').slideUp(200, function() {
  $(this).remove();
});