config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'

  devise_for :users, controllers: {registrations: 'users/registrations'}

  resources :users,only: [:show,:index,:edit,:update]
  get 'users/:id/follows' => "users#follows", as: "follows"
  get 'users/:id/followers' => "users#followers", as: "followers"
  resources :books do
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  post 'follow/:id' => "relationships#create", as: "follow"
  delete 'unfollow/:id' => "relationships#destroy", as: "unfollow"
  get 'search' => "search#action", as: "search"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :comments, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :correct_user, only:[:edit, :update, :destroy]

  def show
		@book = Book.find(params[:id])
		@comment = Comment.new
    @comments = @book.comments.order(created_at: "asc")
  end

  def index
		@books = Book.all.order("id asc")
		@book = Book.new
  end

  def create
  	@book = current_user.books.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to book_path(@book), notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

	def correct_user
		book = Book.find(params[:id])
		unless book.user == current_user
			redirect_to books_url
		end
	end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_favorite.html.erb
<% if Favorite.find_by(user_id: current_user.id, book_id: book.id) %>
  <% @favorite = Favorite.find_by(user_id: current_user.id, book_id: book.id) %>
  <%= link_to book_favorite_path(book_id: book.id, id: @favorite.id), method: :delete, remote: true do %>
    <i class="fas fa-heart"></i>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book_id: book.id), method: :post, remote: true do %>
    <i class="far fa-heart"></i>
  <% end %>
<% end %>
<%= book.favorites.count %>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<%= render "layouts/error", {text: book} %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :opinion %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

  <h1>Editing Book</h1>

  <%= render "books/newform", {book: @book} %>
  <%= link_to "Show", @book, class: "book_#{@book.id}" %>
  <%= link_to "Back", books_path, class: "back" %>

  </div>
</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th style="width:300px">Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td id="favorite-<%= book.id %>">
						<%= render "books/favorite",book: book %>
					</td>
					<td>コメント　(<%= book.comments.count %>)</td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @book.user %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
			<tr>
				<td style="width:120px" class="center">
					<%= link_to (@book.user) do %>
					<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg", size: "100x100") %><br>
					<%= @book.user.name %>
					<% end %>
				</td>
				<td style="width:100px"><%= link_to @book.title, @book %></td>
				<td><%= @book.body %></td>
				<td id="favorite-<%= @book.id %>" style="width:50px">
					<%= render "books/favorite",book: @book %>
				</td>
				<% if @book.user == current_user %>
					<td style="width:50px" class="center"><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td style="width:70px" class="center"><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
				<% end %>
			</tr>
		</table>
		<div class="comment-count">
			<%= render 'comments/count' %>
		</div>
		<hr>
		<div id="comments-area">
			<%= render 'comments/index', comments: @comments %>
		</div>
		<hr>
		<% if user_signed_in? %>
			<div class="comment-create">
				<h3 class="text-left">レビューを投稿する</h3>
				<%= form_for(@comment, url: book_comments_path(@book), remote: true ) do |f| %>
					<%= f.text_area :content, class: "input-mysize form-control" %>
					<%= f.submit "コメントする", class: "btn btn-primary comment-submit float-right right" %>
				<% end %>
			</div>
		<% end %>
		</div>
	</div>
</div>