config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'

  devise_for :users, controllers: {registrations: 'users/registrations'}

  resources :users,only: [:show,:index,:edit,:update]
  get 'users/:id/follows' => "users#follows", as: "follows"
  get 'users/:id/followers' => "users#followers", as: "followers"
  resources :books do
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  post 'follow/:id' => "relationships#create", as: "follow"
  delete 'unfollow/:id' => "relationships#destroy", as: "unfollow"
  get 'search' => "search#action", as: "search"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/_error.html.erb
<!-- エラーメッセージ表示-->
<% if text.errors.any? %>
  <h3><%= text.errors.count %>error occurrence</h3><!--エラーメッセ-->
  <ul>
    <% text.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<!-- エラーメッセージ表示-->

app/views/layouts/_header.html.erb
<!--ヘッダーの記述-->
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <!--if文でサインインとアウト時の表示を変更-->
        <% if user_signed_in? %>
          <li><%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
          <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
        <% else %>
          <li><%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
          <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
          <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<% if user_signed_in? %>
  <%= render "layouts/search" %>
<% end %>
<!--ヘッダーの記述-->

app/views/layouts/_map.html.erb
<div class="row">
	<% if @user == current_user %>
		<h2>Your MAP</h2>
		<div id='map' class="<%= @user.prefecture_code + @user.city + @user.street %>"></div>
	<% end %>
	<style>#map{height: 400px;}</style>
	<script>
	/* mapを関数の外で定義(codeAddressでも使うため)geocoderを用意*/

	let map
	let geocoder

	function initMap(){
		// geocoderを初期化
		geocoder = new google.maps.Geocoder()
		geocoder.geocode( { 'address': $('#map').attr('class')}, function(results, status) {
		if (status == 'OK') {
			map.setCenter(results[0].geometry.location); // map.setCenterで地図が移動
			var marker = new google.maps.Marker({map: map,position: results[0].geometry.location}); // google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
			}else{
				alert('Geocode was not successful for the following reason: ' + status);
			}
		});
		map = new google.maps.Map(document.getElementById('map'), {
		center: {lat: -34.397, lng: 150.644},
		zoom: 8
		});
	}

	function codeAddress(){
		// 入力を取得
		let inputAddress = document.getElementById('address').value;

		// geocodingしたあとmapを移動
	}
	</script>
	<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MAP_API_KEY'] %>&callback=initMap" async defer></script>
</div>

app/views/layouts/_search.html.erb
<div class="row center padding-top30">
  <div class="col-md-12">
    <%= form_tag(search_path, method: :get) do %>
      <input type="text" placeholder="キーワードを入力" name="word" value="">
      <select name="model">
        <option value="1">Users</option>
        <option value="2">Books</option>
      </select>
      <select name="condition">
        <option value="1">完全一致</option>
        <option value="2">前方一致</option>
        <option value="3">後方一致</option>
        <option value="4">部分一致</option>
      </select>
      <input type="submit" value="検索" class="btn-default">
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/64b8b4bea1.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/header" %>
    
    <div class="container">
      <p id="notice" class="padding-top30"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->
    </div>
    <div class="container">
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>